//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DictionaryConsole.DictionaryService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Word", Namespace="http://schemas.datacontract.org/2004/07/Dictionary_Web_Service")]
    [System.SerializableAttribute()]
    public partial class Word : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AdjectiveField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AntonymField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ExampleSentenceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MeaningField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PluralField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PronunciationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SynonymField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TitleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int WordIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Adjective {
            get {
                return this.AdjectiveField;
            }
            set {
                if ((object.ReferenceEquals(this.AdjectiveField, value) != true)) {
                    this.AdjectiveField = value;
                    this.RaisePropertyChanged("Adjective");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Antonym {
            get {
                return this.AntonymField;
            }
            set {
                if ((object.ReferenceEquals(this.AntonymField, value) != true)) {
                    this.AntonymField = value;
                    this.RaisePropertyChanged("Antonym");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ExampleSentence {
            get {
                return this.ExampleSentenceField;
            }
            set {
                if ((object.ReferenceEquals(this.ExampleSentenceField, value) != true)) {
                    this.ExampleSentenceField = value;
                    this.RaisePropertyChanged("ExampleSentence");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Meaning {
            get {
                return this.MeaningField;
            }
            set {
                if ((object.ReferenceEquals(this.MeaningField, value) != true)) {
                    this.MeaningField = value;
                    this.RaisePropertyChanged("Meaning");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Plural {
            get {
                return this.PluralField;
            }
            set {
                if ((object.ReferenceEquals(this.PluralField, value) != true)) {
                    this.PluralField = value;
                    this.RaisePropertyChanged("Plural");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Pronunciation {
            get {
                return this.PronunciationField;
            }
            set {
                if ((object.ReferenceEquals(this.PronunciationField, value) != true)) {
                    this.PronunciationField = value;
                    this.RaisePropertyChanged("Pronunciation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Synonym {
            get {
                return this.SynonymField;
            }
            set {
                if ((object.ReferenceEquals(this.SynonymField, value) != true)) {
                    this.SynonymField = value;
                    this.RaisePropertyChanged("Synonym");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Title {
            get {
                return this.TitleField;
            }
            set {
                if ((object.ReferenceEquals(this.TitleField, value) != true)) {
                    this.TitleField = value;
                    this.RaisePropertyChanged("Title");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int WordId {
            get {
                return this.WordIdField;
            }
            set {
                if ((this.WordIdField.Equals(value) != true)) {
                    this.WordIdField = value;
                    this.RaisePropertyChanged("WordId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="DictionaryService.IDictionaryService")]
    public interface IDictionaryService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDictionaryService/SearchWord", ReplyAction="http://tempuri.org/IDictionaryService/SearchWordResponse")]
        DictionaryConsole.DictionaryService.Word SearchWord(string title);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDictionaryService/SearchWord", ReplyAction="http://tempuri.org/IDictionaryService/SearchWordResponse")]
        System.Threading.Tasks.Task<DictionaryConsole.DictionaryService.Word> SearchWordAsync(string title);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDictionaryServiceChannel : DictionaryConsole.DictionaryService.IDictionaryService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DictionaryServiceClient : System.ServiceModel.ClientBase<DictionaryConsole.DictionaryService.IDictionaryService>, DictionaryConsole.DictionaryService.IDictionaryService {
        
        public DictionaryServiceClient() {
        }
        
        public DictionaryServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DictionaryServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DictionaryServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DictionaryServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public DictionaryConsole.DictionaryService.Word SearchWord(string title) {
            return base.Channel.SearchWord(title);
        }
        
        public System.Threading.Tasks.Task<DictionaryConsole.DictionaryService.Word> SearchWordAsync(string title) {
            return base.Channel.SearchWordAsync(title);
        }
    }
}
